name: linkfs
on:
  push:
    branches:
      - "main"
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '20.8.1'
      - run: bun install
      - run: bun run test
      - run: bun run build
      - run: bun run semantic-release

